
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Server
{

using System;
    using System.Collections.Generic;
    
public partial class user1
{

    public int user_id { get; set; }

    public string user_name { get; set; }

    public string password { get; set; }

    public string last_name { get; set; }

    public string first_name { get; set; }

    public Nullable<int> id_address { get; set; }

    public string addrss_mail { get; set; }

}

}
